@echo off
REM Twine Build Script for Windows
REM Packages the Twine plugin as a WordPress-ready ZIP file

setlocal enabledelayedexpansion

echo ======================================
echo Twine Build
echo ======================================
echo.

REM Get script directory
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

REM Build directory
set "BUILD_DIR=%SCRIPT_DIR%build"

REM Clean previous build
echo Cleaning previous build...
if exist "%BUILD_DIR%" rmdir /s /q "%BUILD_DIR%"
mkdir "%BUILD_DIR%"

REM Get version from latest git tag
echo Reading version from git tags...
for /f "delims=" %%i in ('git describe --tags --match "v*.*.*" 2^>nul') do set GIT_DESCRIBE=%%i
if not defined GIT_DESCRIBE set GIT_DESCRIBE=v0.1.0

REM Parse git describe output (v0.1.0 or v0.1.0-5-g1a2b3c4)
REM Check if there are commits after the tag (contains hyphen after version)
echo %GIT_DESCRIBE% | findstr /R "v[0-9]*\.[0-9]*\.[0-9]*-[0-9]*-g" >nul
if %ERRORLEVEL% EQU 0 (
    REM Format: v0.1.0-5-g1a2b3c4
    REM Extract base version and commit count
    for /f "tokens=1,2 delims=-" %%a in ("%GIT_DESCRIBE:v=%") do (
        set "BASE_VERSION=%%a"
        set "COMMIT_COUNT=%%b"
    )

    REM Parse base version
    for /f "tokens=1,2,3 delims=." %%a in ("!BASE_VERSION!") do (
        set MAJOR=%%a
        set MINOR=%%b
        set MAINTENANCE=%%c-!COMMIT_COUNT!
    )
    set "VERSION=!MAJOR!.!MINOR!.!MAINTENANCE!"
) else (
    REM Exact tag match - no commits after
    set VERSION=%GIT_DESCRIBE:v=%

    REM Parse version components
    for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
        set MAJOR=%%a
        set MINOR=%%b
        set MAINTENANCE=%%c
    )
)

REM Check for uncommitted local changes
git status --porcelain 2>nul | findstr /R ".*" >nul
if %ERRORLEVEL% EQU 0 (
    echo Detected uncommitted changes, appending timestamp
    for /f "tokens=1-4 delims=/:. " %%a in ("%DATE% %TIME%") do (
        set "MONTH=%%b"
        set "DAY=%%c"
        set "HOUR=%%d"
        set "MINUTE=%%e"
    )
    REM Pad single digits with zero
    if "!MONTH:~1!"=="" set "MONTH=0!MONTH!"
    if "!DAY:~1!"=="" set "DAY=0!DAY!"
    if "!HOUR:~1!"=="" set "HOUR=0!HOUR!"
    if "!MINUTE:~1!"=="" set "MINUTE=0!MINUTE!"
    set "TIMESTAMP=!MONTH!!DAY!!HOUR!!MINUTE!"
    set "MAINTENANCE=!MAINTENANCE!-!TIMESTAMP!"
    set "VERSION=!MAJOR!.!MINOR!.!MAINTENANCE!"
)

REM Generate version.properties in build directory
set "VERSION_FILE=%BUILD_DIR%\version.properties"
(
    echo # Twine Version Information
    echo # This file is automatically generated from git tags during the build process.
    echo # Git describe: %GIT_DESCRIBE%
    echo.
    echo major=%MAJOR%
    echo minor=%MINOR%
    echo maintenance=%MAINTENANCE%
) > "%VERSION_FILE%"

echo Building version: %VERSION%
echo.

REM Build Twine Plugin
echo Building Twine plugin...
set "PLUGIN_DIR=%BUILD_DIR%\twine"
mkdir "%PLUGIN_DIR%"

REM Copy plugin files
copy /Y "twine.php" "%PLUGIN_DIR%\" > nul
xcopy /E /I /Q "assets\*" "%PLUGIN_DIR%\assets\" > nul
xcopy /E /I /Q "themes\*" "%PLUGIN_DIR%\themes\" > nul
copy /Y "%VERSION_FILE%" "%PLUGIN_DIR%\" > nul

REM Copy README if it exists
if exist "README.md" copy /Y "README.md" "%PLUGIN_DIR%\" > nul

REM Update version in plugin header
powershell -Command "(Get-Content '%PLUGIN_DIR%\twine.php') -replace '\* Version: .*', '* Version: %VERSION%' | Set-Content '%PLUGIN_DIR%\twine.php'"

REM Remove development files
del /S /Q "%PLUGIN_DIR%\.DS_Store" 2>nul
del /S /Q "%PLUGIN_DIR%\*.swp" 2>nul
del /S /Q "%PLUGIN_DIR%\*.swo" 2>nul
del /S /Q "%PLUGIN_DIR%\*~" 2>nul

REM Create ZIP (requires PowerShell)
cd /d "%BUILD_DIR%"
powershell -Command "Compress-Archive -Path 'twine' -DestinationPath 'twine-%VERSION%.zip' -Force"
echo [32m✓ Created: twine-%VERSION%.zip[0m

REM Clean up temporary directory
cd /d "%SCRIPT_DIR%"
rmdir /s /q "%BUILD_DIR%\twine"

REM Summary
echo.
echo ======================================
echo Build Complete!
echo ======================================
echo.
echo Artifact created in build/:
echo   - twine-%VERSION%.zip
echo.
echo This ZIP file can be uploaded directly to WordPress
echo via Plugins -^> Add New -^> Upload Plugin
echo.

endlocal
pause
