#!/bin/bash

# Twine Build Script
# Packages the Twine plugin as a WordPress-ready ZIP file

set -e  # Exit on error

echo "======================================"
echo "Twine Build"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Build directory
BUILD_DIR="$SCRIPT_DIR/build"

# Clean previous build
echo -e "${BLUE}Cleaning previous build...${NC}"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# Get version from latest git tag
echo -e "${BLUE}Reading version from git tags...${NC}"
GIT_DESCRIBE=$(git describe --tags --match "v*.*.*" 2>/dev/null || echo "v0.1.0")

# Parse git describe output
# Format: v0.1.0 or v0.1.0-5-g1a2b3c4 (if commits exist after tag)
if [[ "$GIT_DESCRIBE" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+)-g([0-9a-f]+))?$ ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    MAINTENANCE="${BASH_REMATCH[3]}"
    COMMIT_COUNT="${BASH_REMATCH[5]}"

    # If there are commits after the tag, append commit count to maintenance
    if [[ -n "$COMMIT_COUNT" ]]; then
        MAINTENANCE="${MAINTENANCE}-${COMMIT_COUNT}"
        VERSION="${MAJOR}.${MINOR}.${MAINTENANCE}"
    else
        VERSION="${MAJOR}.${MINOR}.${MAINTENANCE}"
    fi
else
    # Fallback
    MAJOR=0
    MINOR=1
    MAINTENANCE=0
    VERSION="0.1.0"
fi

# Check for uncommitted local changes
if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
    TIMESTAMP=$(date +"%m%d%H%M")
    MAINTENANCE="${MAINTENANCE}-${TIMESTAMP}"
    VERSION="${MAJOR}.${MINOR}.${MAINTENANCE}"
    echo -e "${BLUE}Detected uncommitted changes, appending timestamp${NC}"
fi

# Generate version.properties in build directory
VERSION_FILE="$BUILD_DIR/version.properties"
cat > "$VERSION_FILE" << EOF
# Twine Version Information
# This file is automatically generated from git tags during the build process.
# Git describe: $GIT_DESCRIBE

major=$MAJOR
minor=$MINOR
maintenance=$MAINTENANCE
EOF

echo -e "${GREEN}Building version: ${VERSION}${NC}"
echo ""

# Build Twine Plugin
echo -e "${BLUE}Building Twine plugin...${NC}"
PLUGIN_DIR="$BUILD_DIR/twine"
mkdir -p "$PLUGIN_DIR"

# Copy plugin files
cp twine.php "$PLUGIN_DIR/"
cp -r assets "$PLUGIN_DIR/"
cp -r themes "$PLUGIN_DIR/"
cp "$VERSION_FILE" "$PLUGIN_DIR/"

# Copy README if it exists
if [ -f "README.md" ]; then
    cp README.md "$PLUGIN_DIR/"
fi

# Update version in plugin header
sed -i.bak "s/\* Version: .*/\* Version: ${VERSION}/" "$PLUGIN_DIR/twine.php"
rm -f "$PLUGIN_DIR/twine.php.bak"

# Remove development files
find "$PLUGIN_DIR" -name ".DS_Store" -delete
find "$PLUGIN_DIR" -name "*.swp" -delete
find "$PLUGIN_DIR" -name "*.swo" -delete
find "$PLUGIN_DIR" -name "*~" -delete

# Create ZIP
cd "$BUILD_DIR"
zip -r "twine-${VERSION}.zip" twine/ -q
echo -e "${GREEN}✓ Created: twine-${VERSION}.zip${NC}"

# Clean up temporary directory
cd "$SCRIPT_DIR"
rm -rf "$BUILD_DIR/twine"

# Summary
echo ""
echo "======================================"
echo -e "${GREEN}Build Complete!${NC}"
echo "======================================"
echo ""
echo "Artifact created in build/:"
echo "  - twine-${VERSION}.zip"
echo ""
echo "This ZIP file can be uploaded directly to WordPress"
echo "via Plugins → Add New → Upload Plugin"
echo ""
